export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  PERSONS: '/persons',
  PERSONS_NEW: '/persons/new',
  PERSONS_EDIT: (id: string) => `/persons/${id}`,
  BUILDINGS: '/buildings',
  BUILDINGS_NEW: '/buildings/new',
  BUILDINGS_EDIT: (id: string) => `/buildings/${id}`,
  EXCURSIONS: '/excursions',
  EXCURSIONS_NEW: '/excursions/new',
  EXCURSIONS_EDIT: (id: string) => `/excursions/${id}`,
  BURIALS: '/burials',
  BURIALS_NEW: '/burials/new',
  BURIALS_EDIT: (id: string) => `/burials/${id}`,
  CEMETERIES: '/cemeteries-admin',
  CEMETERIES_NEW: '/cemeteries-admin/new',
  CEMETERIES_EDIT: (id: string) => `/cemeteries-admin/${id}`,
  USERS: '/users',
} as const;
